/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCaseRouteImport } from './routes/use-case'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentationThunderbirdRouteImport } from './routes/documentation/thunderbird'
import { Route as DocumentationLibreofficeRouteImport } from './routes/documentation/libreoffice'
import { Route as DocumentationInkscapeRouteImport } from './routes/documentation/inkscape'

const UseCaseRoute = UseCaseRouteImport.update({
  id: '/use-case',
  path: '/use-case',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationThunderbirdRoute =
  DocumentationThunderbirdRouteImport.update({
    id: '/thunderbird',
    path: '/thunderbird',
    getParentRoute: () => DocumentationRoute,
  } as any)
const DocumentationLibreofficeRoute =
  DocumentationLibreofficeRouteImport.update({
    id: '/libreoffice',
    path: '/libreoffice',
    getParentRoute: () => DocumentationRoute,
  } as any)
const DocumentationInkscapeRoute = DocumentationInkscapeRouteImport.update({
  id: '/inkscape',
  path: '/inkscape',
  getParentRoute: () => DocumentationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/device': typeof DeviceRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/recommendation': typeof RecommendationRoute
  '/setup': typeof SetupRoute
  '/use-case': typeof UseCaseRoute
  '/documentation/inkscape': typeof DocumentationInkscapeRoute
  '/documentation/libreoffice': typeof DocumentationLibreofficeRoute
  '/documentation/thunderbird': typeof DocumentationThunderbirdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/device': typeof DeviceRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/recommendation': typeof RecommendationRoute
  '/setup': typeof SetupRoute
  '/use-case': typeof UseCaseRoute
  '/documentation/inkscape': typeof DocumentationInkscapeRoute
  '/documentation/libreoffice': typeof DocumentationLibreofficeRoute
  '/documentation/thunderbird': typeof DocumentationThunderbirdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/device': typeof DeviceRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/recommendation': typeof RecommendationRoute
  '/setup': typeof SetupRoute
  '/use-case': typeof UseCaseRoute
  '/documentation/inkscape': typeof DocumentationInkscapeRoute
  '/documentation/libreoffice': typeof DocumentationLibreofficeRoute
  '/documentation/thunderbird': typeof DocumentationThunderbirdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/device'
    | '/documentation'
    | '/recommendation'
    | '/setup'
    | '/use-case'
    | '/documentation/inkscape'
    | '/documentation/libreoffice'
    | '/documentation/thunderbird'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/device'
    | '/documentation'
    | '/recommendation'
    | '/setup'
    | '/use-case'
    | '/documentation/inkscape'
    | '/documentation/libreoffice'
    | '/documentation/thunderbird'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/device'
    | '/documentation'
    | '/recommendation'
    | '/setup'
    | '/use-case'
    | '/documentation/inkscape'
    | '/documentation/libreoffice'
    | '/documentation/thunderbird'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeviceRoute: typeof DeviceRoute
  DocumentationRoute: typeof DocumentationRouteWithChildren
  RecommendationRoute: typeof RecommendationRoute
  SetupRoute: typeof SetupRoute
  UseCaseRoute: typeof UseCaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-case': {
      id: '/use-case'
      path: '/use-case'
      fullPath: '/use-case'
      preLoaderRoute: typeof UseCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/thunderbird': {
      id: '/documentation/thunderbird'
      path: '/thunderbird'
      fullPath: '/documentation/thunderbird'
      preLoaderRoute: typeof DocumentationThunderbirdRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/libreoffice': {
      id: '/documentation/libreoffice'
      path: '/libreoffice'
      fullPath: '/documentation/libreoffice'
      preLoaderRoute: typeof DocumentationLibreofficeRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/inkscape': {
      id: '/documentation/inkscape'
      path: '/inkscape'
      fullPath: '/documentation/inkscape'
      preLoaderRoute: typeof DocumentationInkscapeRouteImport
      parentRoute: typeof DocumentationRoute
    }
  }
}

interface DocumentationRouteChildren {
  DocumentationInkscapeRoute: typeof DocumentationInkscapeRoute
  DocumentationLibreofficeRoute: typeof DocumentationLibreofficeRoute
  DocumentationThunderbirdRoute: typeof DocumentationThunderbirdRoute
}

const DocumentationRouteChildren: DocumentationRouteChildren = {
  DocumentationInkscapeRoute: DocumentationInkscapeRoute,
  DocumentationLibreofficeRoute: DocumentationLibreofficeRoute,
  DocumentationThunderbirdRoute: DocumentationThunderbirdRoute,
}

const DocumentationRouteWithChildren = DocumentationRoute._addFileChildren(
  DocumentationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeviceRoute: DeviceRoute,
  DocumentationRoute: DocumentationRouteWithChildren,
  RecommendationRoute: RecommendationRoute,
  SetupRoute: SetupRoute,
  UseCaseRoute: UseCaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
